// Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.

#ifndef _athub_5_0_1_OFFSET_HEADER
#define _athub_5_0_1_OFFSET_HEADER



// addressBlock: athub_atsdec
// base address: 0x2c80
#define regATC_PERFCOUNTER0_CFG                                                                         0x0000
#define regATC_PERFCOUNTER0_CFG_BASE_IDX                                                                0
#define regATC_PERFCOUNTER1_CFG                                                                         0x0001
#define regATC_PERFCOUNTER1_CFG_BASE_IDX                                                                0
#define regATC_PERFCOUNTER2_CFG                                                                         0x0002
#define regATC_PERFCOUNTER2_CFG_BASE_IDX                                                                0
#define regATC_PERFCOUNTER3_CFG                                                                         0x0003
#define regATC_PERFCOUNTER3_CFG_BASE_IDX                                                                0
#define regATC_PERFCOUNTER_RSLT_CNTL                                                                    0x0004
#define regATC_PERFCOUNTER_RSLT_CNTL_BASE_IDX                                                           0
#define regATC_PERFCOUNTER_LO                                                                           0x0005
#define regATC_PERFCOUNTER_LO_BASE_IDX                                                                  0
#define regATC_PERFCOUNTER_HI                                                                           0x0006
#define regATC_PERFCOUNTER_HI_BASE_IDX                                                                  0
#define regATC_ATS_STATUS                                                                               0x0007
#define regATC_ATS_STATUS_BASE_IDX                                                                      0
#define regATC_ATS_MISC_CNTL                                                                            0x0008
#define regATC_ATS_MISC_CNTL_BASE_IDX                                                                   0
#define regATC_ATS_CNTL                                                                                 0x0009
#define regATC_ATS_CNTL_BASE_IDX                                                                        0
#define regATC_ATS_CNTL2                                                                                0x000a
#define regATC_ATS_CNTL2_BASE_IDX                                                                       0
#define regATC_ATS_CNTL3                                                                                0x000b
#define regATC_ATS_CNTL3_BASE_IDX                                                                       0
#define regATC_ATS_CNTL4                                                                                0x000c
#define regATC_ATS_CNTL4_BASE_IDX                                                                       0
#define regATC_ATS_CNTL5                                                                                0x000d
#define regATC_ATS_CNTL5_BASE_IDX                                                                       0
#define regATC_ATS_DEBUG                                                                                0x000e
#define regATC_ATS_DEBUG_BASE_IDX                                                                       0
#define regATC_ATS_DEBUG2                                                                               0x000f
#define regATC_ATS_DEBUG2_BASE_IDX                                                                      0
#define regATC_ATS_DEBUG3                                                                               0x0010
#define regATC_ATS_DEBUG3_BASE_IDX                                                                      0
#define regATC_ATS_FAULT_DEBUG                                                                          0x0011
#define regATC_ATS_FAULT_DEBUG_BASE_IDX                                                                 0
#define regATC_ATS_FAULT_CNTL                                                                           0x0012
#define regATC_ATS_FAULT_CNTL_BASE_IDX                                                                  0
#define regATC_ATS_FAULT_STATUS_INFO                                                                    0x0013
#define regATC_ATS_FAULT_STATUS_INFO_BASE_IDX                                                           0
#define regATC_ATS_FAULT_STATUS_INFO2                                                                   0x0014
#define regATC_ATS_FAULT_STATUS_INFO2_BASE_IDX                                                          0
#define regATC_ATS_FAULT_STATUS_INFO3                                                                   0x0015
#define regATC_ATS_FAULT_STATUS_INFO3_BASE_IDX                                                          0
#define regATC_ATS_FAULT_STATUS_INFO4                                                                   0x0016
#define regATC_ATS_FAULT_STATUS_INFO4_BASE_IDX                                                          0
#define regATC_ATS_FAULT_STATUS_ADDR                                                                    0x0017
#define regATC_ATS_FAULT_STATUS_ADDR_BASE_IDX                                                           0
#define regATC_ATS_DEFAULT_PAGE_LOW                                                                     0x0018
#define regATC_ATS_DEFAULT_PAGE_LOW_BASE_IDX                                                            0
#define regATC_ATS_DEFAULT_PAGE_HIGH                                                                    0x0019
#define regATC_ATS_DEFAULT_PAGE_HIGH_BASE_IDX                                                           0
#define regATC_ATS_CONFIG_CNTL_0                                                                        0x001a
#define regATC_ATS_CONFIG_CNTL_0_BASE_IDX                                                               0
#define regATC_ATS_CONFIG_CNTL_1                                                                        0x001b
#define regATC_ATS_CONFIG_CNTL_1_BASE_IDX                                                               0
#define regATC_ATS_NODE_MAPPING_0                                                                       0x001c
#define regATC_ATS_NODE_MAPPING_0_BASE_IDX                                                              0
#define regATC_ATS_NODE_MAPPING_1                                                                       0x001d
#define regATC_ATS_NODE_MAPPING_1_BASE_IDX                                                              0
#define regATC_ATS_NODE_MAPPING_2                                                                       0x001e
#define regATC_ATS_NODE_MAPPING_2_BASE_IDX                                                              0
#define regATHUB_PCIE_ATS_CNTL                                                                          0x001f
#define regATHUB_PCIE_ATS_CNTL_BASE_IDX                                                                 0
#define regATHUB_COMMAND                                                                                0x0020
#define regATHUB_COMMAND_BASE_IDX                                                                       0
#define regATHUB_PCIE_PAGE_REQ_CNTL                                                                     0x0021
#define regATHUB_PCIE_PAGE_REQ_CNTL_BASE_IDX                                                            0
#define regATHUB_PCIE_OUTSTAND_PAGE_REQ_ALLOC                                                           0x0022
#define regATHUB_PCIE_OUTSTAND_PAGE_REQ_ALLOC_BASE_IDX                                                  0
#define regATC_ATS_ATCL2_PD_CNTL                                                                        0x0023
#define regATC_ATS_ATCL2_PD_CNTL_BASE_IDX                                                               0
#define regATC_ATS_ATCL2_PD_CNTL1                                                                       0x0024
#define regATC_ATS_ATCL2_PD_CNTL1_BASE_IDX                                                              0
#define regATC_ATS_SDPPORT_CNTL                                                                         0x0025
#define regATC_ATS_SDPPORT_CNTL_BASE_IDX                                                                0
#define regATC_ATS_SDPPORT_CREDITS                                                                      0x0026
#define regATC_ATS_SDPPORT_CREDITS_BASE_IDX                                                             0
#define regATC_ATS_SDP_STATUS                                                                           0x0027
#define regATC_ATS_SDP_STATUS_BASE_IDX                                                                  0
#define regATC_ATS_SDPPORT_QOSPRIORITY_1                                                                0x0028
#define regATC_ATS_SDPPORT_QOSPRIORITY_1_BASE_IDX                                                       0
#define regATC_ATS_SDPPORT_QOSPRIORITY_2                                                                0x0029
#define regATC_ATS_SDPPORT_QOSPRIORITY_2_BASE_IDX                                                       0
#define regATHUB_IH_CREDIT                                                                              0x002e
#define regATHUB_IH_CREDIT_BASE_IDX                                                                     0
#define regATHUB_IH_COOKIE0_ADDR_LOW                                                                    0x002f
#define regATHUB_IH_COOKIE0_ADDR_LOW_BASE_IDX                                                           0
#define regATHUB_IH_COOKIE0_ADDR_HIGH                                                                   0x0030
#define regATHUB_IH_COOKIE0_ADDR_HIGH_BASE_IDX                                                          0
#define regATC_ATS_AT_QOS_CNTL                                                                          0x0031
#define regATC_ATS_AT_QOS_CNTL_BASE_IDX                                                                 0
#define regATHUB_MCA_RAS_INTR_CTRL_ADDR_LOW                                                             0x0032
#define regATHUB_MCA_RAS_INTR_CTRL_ADDR_LOW_BASE_IDX                                                    0
#define regATHUB_MCA_RAS_INTR_CTRL_ADDR_HIGH                                                            0x0033
#define regATHUB_MCA_RAS_INTR_CTRL_ADDR_HIGH_BASE_IDX                                                   0
#define regATHUB_RAS_CNTL                                                                               0x0034
#define regATHUB_RAS_CNTL_BASE_IDX                                                                      0
#define regATS_LOGGING                                                                                  0x0035
#define regATS_LOGGING_BASE_IDX                                                                         0
#define regATS_POISON_INT_CNTL                                                                          0x0036
#define regATS_POISON_INT_CNTL_BASE_IDX                                                                 0
#define regATHUB_ATS_MODE_CNTL                                                                          0x0037
#define regATHUB_ATS_MODE_CNTL_BASE_IDX                                                                 0
#define regATC_ATS_INVALIDATION_OUTSTANDING                                                             0x0038
#define regATC_ATS_INVALIDATION_OUTSTANDING_BASE_IDX                                                    0
#define regATC_ATS_TR_QOS_CNTL                                                                          0x0039
#define regATC_ATS_TR_QOS_CNTL_BASE_IDX                                                                 0


// addressBlock: athub_xpbdec
// base address: 0x2e80
#define regXPB_RTR_SRC_APRTR0                                                                           0x0080
#define regXPB_RTR_SRC_APRTR0_BASE_IDX                                                                  0
#define regXPB_RTR_SRC_APRTR1                                                                           0x0081
#define regXPB_RTR_SRC_APRTR1_BASE_IDX                                                                  0
#define regXPB_RTR_SRC_APRTR2                                                                           0x0082
#define regXPB_RTR_SRC_APRTR2_BASE_IDX                                                                  0
#define regXPB_RTR_SRC_APRTR3                                                                           0x0083
#define regXPB_RTR_SRC_APRTR3_BASE_IDX                                                                  0
#define regXPB_RTR_SRC_APRTR4                                                                           0x0084
#define regXPB_RTR_SRC_APRTR4_BASE_IDX                                                                  0
#define regXPB_RTR_SRC_APRTR5                                                                           0x0085
#define regXPB_RTR_SRC_APRTR5_BASE_IDX                                                                  0
#define regXPB_RTR_SRC_APRTR6                                                                           0x0086
#define regXPB_RTR_SRC_APRTR6_BASE_IDX                                                                  0
#define regXPB_RTR_SRC_APRTR7                                                                           0x0087
#define regXPB_RTR_SRC_APRTR7_BASE_IDX                                                                  0
#define regXPB_RTR_SRC_APRTR8                                                                           0x0088
#define regXPB_RTR_SRC_APRTR8_BASE_IDX                                                                  0
#define regXPB_RTR_SRC_APRTR9                                                                           0x0089
#define regXPB_RTR_SRC_APRTR9_BASE_IDX                                                                  0
#define regXPB_RTR_SRC_APRTR10                                                                          0x008a
#define regXPB_RTR_SRC_APRTR10_BASE_IDX                                                                 0
#define regXPB_RTR_SRC_APRTR11                                                                          0x008b
#define regXPB_RTR_SRC_APRTR11_BASE_IDX                                                                 0
#define regXPB_RTR_SRC_APRTR12                                                                          0x008c
#define regXPB_RTR_SRC_APRTR12_BASE_IDX                                                                 0
#define regXPB_RTR_SRC_APRTR13                                                                          0x008d
#define regXPB_RTR_SRC_APRTR13_BASE_IDX                                                                 0
#define regXPB_RTR_DEST_MAP0                                                                            0x008e
#define regXPB_RTR_DEST_MAP0_BASE_IDX                                                                   0
#define regXPB_RTR_DEST_MAP1                                                                            0x008f
#define regXPB_RTR_DEST_MAP1_BASE_IDX                                                                   0
#define regXPB_RTR_DEST_MAP2                                                                            0x0090
#define regXPB_RTR_DEST_MAP2_BASE_IDX                                                                   0
#define regXPB_RTR_DEST_MAP3                                                                            0x0091
#define regXPB_RTR_DEST_MAP3_BASE_IDX                                                                   0
#define regXPB_RTR_DEST_MAP4                                                                            0x0092
#define regXPB_RTR_DEST_MAP4_BASE_IDX                                                                   0
#define regXPB_RTR_DEST_MAP5                                                                            0x0093
#define regXPB_RTR_DEST_MAP5_BASE_IDX                                                                   0
#define regXPB_RTR_DEST_MAP6                                                                            0x0094
#define regXPB_RTR_DEST_MAP6_BASE_IDX                                                                   0
#define regXPB_RTR_DEST_MAP7                                                                            0x0095
#define regXPB_RTR_DEST_MAP7_BASE_IDX                                                                   0
#define regXPB_RTR_DEST_MAP8                                                                            0x0096
#define regXPB_RTR_DEST_MAP8_BASE_IDX                                                                   0
#define regXPB_RTR_DEST_MAP9                                                                            0x0097
#define regXPB_RTR_DEST_MAP9_BASE_IDX                                                                   0
#define regXPB_RTR_DEST_MAP10                                                                           0x0098
#define regXPB_RTR_DEST_MAP10_BASE_IDX                                                                  0
#define regXPB_RTR_DEST_MAP11                                                                           0x0099
#define regXPB_RTR_DEST_MAP11_BASE_IDX                                                                  0
#define regXPB_RTR_DEST_MAP12                                                                           0x009a
#define regXPB_RTR_DEST_MAP12_BASE_IDX                                                                  0
#define regXPB_RTR_DEST_MAP13                                                                           0x009b
#define regXPB_RTR_DEST_MAP13_BASE_IDX                                                                  0
#define regXPB_CLG_CFG0                                                                                 0x009c
#define regXPB_CLG_CFG0_BASE_IDX                                                                        0
#define regXPB_CLG_CFG1                                                                                 0x009d
#define regXPB_CLG_CFG1_BASE_IDX                                                                        0
#define regXPB_CLG_CFG2                                                                                 0x009e
#define regXPB_CLG_CFG2_BASE_IDX                                                                        0
#define regXPB_CLG_CFG3                                                                                 0x009f
#define regXPB_CLG_CFG3_BASE_IDX                                                                        0
#define regXPB_CLG_CFG4                                                                                 0x00a0
#define regXPB_CLG_CFG4_BASE_IDX                                                                        0
#define regXPB_CLG_CFG5                                                                                 0x00a1
#define regXPB_CLG_CFG5_BASE_IDX                                                                        0
#define regXPB_CLG_CFG6                                                                                 0x00a2
#define regXPB_CLG_CFG6_BASE_IDX                                                                        0
#define regXPB_CLG_CFG7                                                                                 0x00a3
#define regXPB_CLG_CFG7_BASE_IDX                                                                        0
#define regXPB_CLG_EXTRA0                                                                               0x00a4
#define regXPB_CLG_EXTRA0_BASE_IDX                                                                      0
#define regXPB_CLG_EXTRA1                                                                               0x00a5
#define regXPB_CLG_EXTRA1_BASE_IDX                                                                      0
#define regXPB_CLG_EXTRA_MSK                                                                            0x00a6
#define regXPB_CLG_EXTRA_MSK_BASE_IDX                                                                   0
#define regXPB_LB_ADDR                                                                                  0x00a7
#define regXPB_LB_ADDR_BASE_IDX                                                                         0
#define regXPB_HST_CFG                                                                                  0x00a8
#define regXPB_HST_CFG_BASE_IDX                                                                         0
#define regXPB_P2P_BAR_CFG                                                                              0x00a9
#define regXPB_P2P_BAR_CFG_BASE_IDX                                                                     0
#define regXPB_P2P_BAR0                                                                                 0x00aa
#define regXPB_P2P_BAR0_BASE_IDX                                                                        0
#define regXPB_P2P_BAR1                                                                                 0x00ab
#define regXPB_P2P_BAR1_BASE_IDX                                                                        0
#define regXPB_P2P_BAR2                                                                                 0x00ac
#define regXPB_P2P_BAR2_BASE_IDX                                                                        0
#define regXPB_P2P_BAR3                                                                                 0x00ad
#define regXPB_P2P_BAR3_BASE_IDX                                                                        0
#define regXPB_P2P_BAR4                                                                                 0x00ae
#define regXPB_P2P_BAR4_BASE_IDX                                                                        0
#define regXPB_P2P_BAR5                                                                                 0x00af
#define regXPB_P2P_BAR5_BASE_IDX                                                                        0
#define regXPB_P2P_BAR6                                                                                 0x00b0
#define regXPB_P2P_BAR6_BASE_IDX                                                                        0
#define regXPB_P2P_BAR7                                                                                 0x00b1
#define regXPB_P2P_BAR7_BASE_IDX                                                                        0
#define regXPB_P2P_BAR_SETUP                                                                            0x00b2
#define regXPB_P2P_BAR_SETUP_BASE_IDX                                                                   0
#define regXPB_P2P_BAR_DEBUG                                                                            0x00b3
#define regXPB_P2P_BAR_DEBUG_BASE_IDX                                                                   0
#define regXPB_P2P_BAR_DELTA_ABOVE                                                                      0x00b4
#define regXPB_P2P_BAR_DELTA_ABOVE_BASE_IDX                                                             0
#define regXPB_P2P_BAR_DELTA_BELOW                                                                      0x00b5
#define regXPB_P2P_BAR_DELTA_BELOW_BASE_IDX                                                             0
#define regXPB_PEER_SYS_BAR0                                                                            0x00b6
#define regXPB_PEER_SYS_BAR0_BASE_IDX                                                                   0
#define regXPB_PEER_SYS_BAR1                                                                            0x00b7
#define regXPB_PEER_SYS_BAR1_BASE_IDX                                                                   0
#define regXPB_PEER_SYS_BAR2                                                                            0x00b8
#define regXPB_PEER_SYS_BAR2_BASE_IDX                                                                   0
#define regXPB_PEER_SYS_BAR3                                                                            0x00b9
#define regXPB_PEER_SYS_BAR3_BASE_IDX                                                                   0
#define regXPB_PEER_SYS_BAR4                                                                            0x00ba
#define regXPB_PEER_SYS_BAR4_BASE_IDX                                                                   0
#define regXPB_PEER_SYS_BAR5                                                                            0x00bb
#define regXPB_PEER_SYS_BAR5_BASE_IDX                                                                   0
#define regXPB_PEER_SYS_BAR6                                                                            0x00bc
#define regXPB_PEER_SYS_BAR6_BASE_IDX                                                                   0
#define regXPB_PEER_SYS_BAR7                                                                            0x00bd
#define regXPB_PEER_SYS_BAR7_BASE_IDX                                                                   0
#define regXPB_PEER_SYS_BAR8                                                                            0x00be
#define regXPB_PEER_SYS_BAR8_BASE_IDX                                                                   0
#define regXPB_PEER_SYS_BAR9                                                                            0x00bf
#define regXPB_PEER_SYS_BAR9_BASE_IDX                                                                   0
#define regXPB_PEER_SYS_BAR10                                                                           0x00c0
#define regXPB_PEER_SYS_BAR10_BASE_IDX                                                                  0
#define regXPB_PEER_SYS_BAR11                                                                           0x00c1
#define regXPB_PEER_SYS_BAR11_BASE_IDX                                                                  0
#define regXPB_PEER_SYS_BAR12                                                                           0x00c2
#define regXPB_PEER_SYS_BAR12_BASE_IDX                                                                  0
#define regXPB_PEER_SYS_BAR13                                                                           0x00c3
#define regXPB_PEER_SYS_BAR13_BASE_IDX                                                                  0
#define regXPB_CLK_GAT                                                                                  0x00c4
#define regXPB_CLK_GAT_BASE_IDX                                                                         0
#define regXPB_INTF_CFG                                                                                 0x00c5
#define regXPB_INTF_CFG_BASE_IDX                                                                        0
#define regXPB_INTF_STS                                                                                 0x00c6
#define regXPB_INTF_STS_BASE_IDX                                                                        0
#define regXPB_PIPE_STS                                                                                 0x00c7
#define regXPB_PIPE_STS_BASE_IDX                                                                        0
#define regXPB_WCB_STS                                                                                  0x00c8
#define regXPB_WCB_STS_BASE_IDX                                                                         0
#define regXPB_MAP_INVERT_FLUSH_NUM_LSB                                                                 0x00c9
#define regXPB_MAP_INVERT_FLUSH_NUM_LSB_BASE_IDX                                                        0
#define regXPB_STICKY                                                                                   0x00ca
#define regXPB_STICKY_BASE_IDX                                                                          0
#define regXPB_STICKY_W1C                                                                               0x00cb
#define regXPB_STICKY_W1C_BASE_IDX                                                                      0
#define regXPB_SUB_CTRL                                                                                 0x00cc
#define regXPB_SUB_CTRL_BASE_IDX                                                                        0
#define regXPB_PERF_KNOBS                                                                               0x00cd
#define regXPB_PERF_KNOBS_BASE_IDX                                                                      0
#define regXPB_MISC_CFG                                                                                 0x00ce
#define regXPB_MISC_CFG_BASE_IDX                                                                        0
#define regXPB_INTF_CFG2                                                                                0x00cf
#define regXPB_INTF_CFG2_BASE_IDX                                                                       0
#define regXPB_CLG_EXTRA_RD                                                                             0x00d0
#define regXPB_CLG_EXTRA_RD_BASE_IDX                                                                    0
#define regXPB_CLG_EXTRA_MSK_RD                                                                         0x00d1
#define regXPB_CLG_EXTRA_MSK_RD_BASE_IDX                                                                0
#define regXPB_CLG_GFX_MATCH                                                                            0x00d2
#define regXPB_CLG_GFX_MATCH_BASE_IDX                                                                   0
#define regXPB_CLG_GFX_MATCH_VLD                                                                        0x00d3
#define regXPB_CLG_GFX_MATCH_VLD_BASE_IDX                                                               0
#define regXPB_CLG_GFX_MATCH_MSK                                                                        0x00d4
#define regXPB_CLG_GFX_MATCH_MSK_BASE_IDX                                                               0
#define regXPB_CLG_MM_MATCH                                                                             0x00d5
#define regXPB_CLG_MM_MATCH_BASE_IDX                                                                    0
#define regXPB_CLG_MM_MATCH_VLD                                                                         0x00d6
#define regXPB_CLG_MM_MATCH_VLD_BASE_IDX                                                                0
#define regXPB_CLG_MM_MATCH_MSK                                                                         0x00d7
#define regXPB_CLG_MM_MATCH_MSK_BASE_IDX                                                                0
#define regXPB_CLG_OTHERS_MATCH                                                                         0x00d8
#define regXPB_CLG_OTHERS_MATCH_BASE_IDX                                                                0
#define regXPB_CLG_OTHERS_MATCH_MSK                                                                     0x00d9
#define regXPB_CLG_OTHERS_MATCH_MSK_BASE_IDX                                                            0
#define regXPB_CLG_GFX_UNITID_MAPPING0                                                                  0x00da
#define regXPB_CLG_GFX_UNITID_MAPPING0_BASE_IDX                                                         0
#define regXPB_CLG_GFX_UNITID_MAPPING1                                                                  0x00db
#define regXPB_CLG_GFX_UNITID_MAPPING1_BASE_IDX                                                         0
#define regXPB_CLG_GFX_UNITID_MAPPING2                                                                  0x00dc
#define regXPB_CLG_GFX_UNITID_MAPPING2_BASE_IDX                                                         0
#define regXPB_CLG_GFX_UNITID_MAPPING3                                                                  0x00dd
#define regXPB_CLG_GFX_UNITID_MAPPING3_BASE_IDX                                                         0
#define regXPB_CLG_GFX_UNITID_MAPPING4                                                                  0x00de
#define regXPB_CLG_GFX_UNITID_MAPPING4_BASE_IDX                                                         0
#define regXPB_CLG_GFX_UNITID_MAPPING5                                                                  0x00df
#define regXPB_CLG_GFX_UNITID_MAPPING5_BASE_IDX                                                         0
#define regXPB_CLG_GFX_UNITID_MAPPING6                                                                  0x00e0
#define regXPB_CLG_GFX_UNITID_MAPPING6_BASE_IDX                                                         0
#define regXPB_CLG_GFX_UNITID_MAPPING7                                                                  0x00e1
#define regXPB_CLG_GFX_UNITID_MAPPING7_BASE_IDX                                                         0
#define regXPB_CLG_MM_UNITID_MAPPING0                                                                   0x00e2
#define regXPB_CLG_MM_UNITID_MAPPING0_BASE_IDX                                                          0
#define regXPB_CLG_MM_UNITID_MAPPING1                                                                   0x00e3
#define regXPB_CLG_MM_UNITID_MAPPING1_BASE_IDX                                                          0
#define regXPB_CLG_MM_UNITID_MAPPING2                                                                   0x00e4
#define regXPB_CLG_MM_UNITID_MAPPING2_BASE_IDX                                                          0
#define regXPB_CLG_MM_UNITID_MAPPING3                                                                   0x00e5
#define regXPB_CLG_MM_UNITID_MAPPING3_BASE_IDX                                                          0
#define regXPB_CLG_OTHERS_UNITID_MAPPING0                                                               0x00e6
#define regXPB_CLG_OTHERS_UNITID_MAPPING0_BASE_IDX                                                      0
#define regXPB_CLG_OTHERS_UNITID_MAPPING1                                                               0x00e7
#define regXPB_CLG_OTHERS_UNITID_MAPPING1_BASE_IDX                                                      0
#define regXPB_CLG_OTHERS_UNITID_MAPPING2                                                               0x00e8
#define regXPB_CLG_OTHERS_UNITID_MAPPING2_BASE_IDX                                                      0
#define regXPB_CLG_OTHERS_UNITID_MAPPING3                                                               0x00e9
#define regXPB_CLG_OTHERS_UNITID_MAPPING3_BASE_IDX                                                      0
#define regXPB_CLG_OTHERS_UNITID_MAPPING4                                                               0x00ea
#define regXPB_CLG_OTHERS_UNITID_MAPPING4_BASE_IDX                                                      0
#define regXPB_CLG_OTHERS_UNITID_MAPPING5                                                               0x00eb
#define regXPB_CLG_OTHERS_UNITID_MAPPING5_BASE_IDX                                                      0
#define regXPB_CLG_OTHERS_UNITID_MAPPING6                                                               0x00ec
#define regXPB_CLG_OTHERS_UNITID_MAPPING6_BASE_IDX                                                      0
#define regXPB_CLG_OTHERS_UNITID_MAPPING7                                                               0x00ed
#define regXPB_CLG_OTHERS_UNITID_MAPPING7_BASE_IDX                                                      0
#define regXPB_HDP_XDP_D2H_ADDR_CONFIG                                                                  0x00ee
#define regXPB_HDP_XDP_D2H_ADDR_CONFIG_BASE_IDX                                                         0


// addressBlock: athub_rpbdec
// base address: 0x3080
#define regRPB_DBG2                                                                                     0x0100
#define regRPB_DBG2_BASE_IDX                                                                            0
#define regRPB_ERR_INJECT                                                                               0x010d
#define regRPB_ERR_INJECT_BASE_IDX                                                                      0
#define regRPB_NCS_SDP_ERRINJ                                                                           0x010e
#define regRPB_NCS_SDP_ERRINJ_BASE_IDX                                                                  0
#define regRPB_NBIF_SDP_ERRINJ                                                                          0x010f
#define regRPB_NBIF_SDP_ERRINJ_BASE_IDX                                                                 0
#define regRPB_NCS_SDP_REQ_OBSERVE                                                                      0x0110
#define regRPB_NCS_SDP_REQ_OBSERVE_BASE_IDX                                                             0
#define regRPB_NCS_SDP_RDRSP_OBSERVE                                                                    0x0111
#define regRPB_NCS_SDP_RDRSP_OBSERVE_BASE_IDX                                                           0
#define regRPB_NBIF_SDP_REQ_OBSERVE                                                                     0x0112
#define regRPB_NBIF_SDP_REQ_OBSERVE_BASE_IDX                                                            0
#define regRPB_NBIF_SDP_RDRSP_OBSERVE                                                                   0x0113
#define regRPB_NBIF_SDP_RDRSP_OBSERVE_BASE_IDX                                                          0
#define regATHUB_SHARED_VIRT_RESET_REQ                                                                  0x0114
#define regATHUB_SHARED_VIRT_RESET_REQ_BASE_IDX                                                         0
#define regATHUB_SHARED_PF_RESET_REQ                                                                    0x0115
#define regATHUB_SHARED_PF_RESET_REQ_BASE_IDX                                                           0
#define regRPB_SECLEVEL_CONF                                                                            0x0116
#define regRPB_SECLEVEL_CONF_BASE_IDX                                                                   0
#define regATHUB_MEM_POWER_LS                                                                           0x0118
#define regATHUB_MEM_POWER_LS_BASE_IDX                                                                  0
#define regATHUB_MISC_CNTL                                                                              0x0119
#define regATHUB_MISC_CNTL_BASE_IDX                                                                     0
#define regATHUB_MISC_CG_CNTL                                                                           0x011a
#define regATHUB_MISC_CG_CNTL_BASE_IDX                                                                  0
#define regATHUB_DS_ALLOW_CNTL                                                                          0x011b
#define regATHUB_DS_ALLOW_CNTL_BASE_IDX                                                                 0
#define regRPB_PASSPW_CONF                                                                              0x011c
#define regRPB_PASSPW_CONF_BASE_IDX                                                                     0
#define regRPB_BLOCKLEVEL_CONF                                                                          0x011d
#define regRPB_BLOCKLEVEL_CONF_BASE_IDX                                                                 0
#define regRPB_TAG_CONF                                                                                 0x011e
#define regRPB_TAG_CONF_BASE_IDX                                                                        0
#define regRPB_DBG1                                                                                     0x011f
#define regRPB_DBG1_BASE_IDX                                                                            0
#define regRPB_ARB_CNTL                                                                                 0x0120
#define regRPB_ARB_CNTL_BASE_IDX                                                                        0
#define regRPB_ARB_CNTL2                                                                                0x0121
#define regRPB_ARB_CNTL2_BASE_IDX                                                                       0
#define regRPB_BIF_CNTL                                                                                 0x0122
#define regRPB_BIF_CNTL_BASE_IDX                                                                        0
#define regRPB_BIF_CNTL2                                                                                0x0123
#define regRPB_BIF_CNTL2_BASE_IDX                                                                       0
#define regRPB_SDPPORT_CNTL                                                                             0x0124
#define regRPB_SDPPORT_CNTL_BASE_IDX                                                                    0
#define regRPB_NBIF_SDPPORT_CNTL                                                                        0x0125
#define regRPB_NBIF_SDPPORT_CNTL_BASE_IDX                                                               0
#define regRPB_NBIF_SDPPORT_CNTL2                                                                       0x0126
#define regRPB_NBIF_SDPPORT_CNTL2_BASE_IDX                                                              0
#define regRPB_DEINTRLV_COMBINE_CNTL                                                                    0x0127
#define regRPB_DEINTRLV_COMBINE_CNTL_BASE_IDX                                                           0
#define regRPB_VC_SWITCH_RDWR                                                                           0x0128
#define regRPB_VC_SWITCH_RDWR_BASE_IDX                                                                  0
#define regRPB_ATS_CNTL3                                                                                0x0129
#define regRPB_ATS_CNTL3_BASE_IDX                                                                       0
#define regRPB_DF_SDPPORT_CNTL                                                                          0x012a
#define regRPB_DF_SDPPORT_CNTL_BASE_IDX                                                                 0
#define regRPB_ATS_CNTL                                                                                 0x012b
#define regRPB_ATS_CNTL_BASE_IDX                                                                        0
#define regRPB_ATS_CNTL2                                                                                0x012c
#define regRPB_ATS_CNTL2_BASE_IDX                                                                       0
#define regRPB_ZFB_CONFIG                                                                               0x012d
#define regRPB_ZFB_CONFIG_BASE_IDX                                                                      0
#define regRPB_PERFCOUNTER0_CFG                                                                         0x012e
#define regRPB_PERFCOUNTER0_CFG_BASE_IDX                                                                0
#define regRPB_PERFCOUNTER1_CFG                                                                         0x012f
#define regRPB_PERFCOUNTER1_CFG_BASE_IDX                                                                0
#define regRPB_PERFCOUNTER2_CFG                                                                         0x0130
#define regRPB_PERFCOUNTER2_CFG_BASE_IDX                                                                0
#define regRPB_PERFCOUNTER3_CFG                                                                         0x0131
#define regRPB_PERFCOUNTER3_CFG_BASE_IDX                                                                0
#define regRPB_PERFCOUNTER_RSLT_CNTL                                                                    0x0132
#define regRPB_PERFCOUNTER_RSLT_CNTL_BASE_IDX                                                           0
#define regRPB_PERF_COUNTER_CNTL                                                                        0x0133
#define regRPB_PERF_COUNTER_CNTL_BASE_IDX                                                               0
#define regRPB_PERFCOUNTER_HI                                                                           0x0134
#define regRPB_PERFCOUNTER_HI_BASE_IDX                                                                  0
#define regRPB_PERFCOUNTER_LO                                                                           0x0135
#define regRPB_PERFCOUNTER_LO_BASE_IDX                                                                  0
#define regRPB_PERF_COUNTER_STATUS                                                                      0x0136
#define regRPB_PERF_COUNTER_STATUS_BASE_IDX                                                             0
#define regRPB_PERF_DF_LATENCY_SAMPLING                                                                 0x0137
#define regRPB_PERF_DF_LATENCY_SAMPLING_BASE_IDX                                                        0
#define regRPB_PERF_DMA_LATENCY_SAMPLING                                                                0x0138
#define regRPB_PERF_DMA_LATENCY_SAMPLING_BASE_IDX                                                       0


// addressBlock: athub_mca_athub_mca_map
// base address: 0x3280
#define regMCathub_CTLT0                                                                                0x0180
#define regMCathub_CTLT0_BASE_IDX                                                                       0
#define regMCathub_STATUST0                                                                             0x0182
#define regMCathub_STATUST0_BASE_IDX                                                                    0
#define regMCathub_ADDRT0                                                                               0x0184
#define regMCathub_ADDRT0_BASE_IDX                                                                      0
#define regMCathub_MISC0T0                                                                              0x0186
#define regMCathub_MISC0T0_BASE_IDX                                                                     0
#define regMCathub_CONFIGT0                                                                             0x0188
#define regMCathub_CONFIGT0_BASE_IDX                                                                    0
#define regMCathub_IPIDT0                                                                               0x018a
#define regMCathub_IPIDT0_BASE_IDX                                                                      0
#define regMCathub_SYNDT0                                                                               0x018c
#define regMCathub_SYNDT0_BASE_IDX                                                                      0
#define regMCathub_SYND1T0                                                                              0x019c
#define regMCathub_SYND1T0_BASE_IDX                                                                     0
#define regMCathub_SYND2T0                                                                              0x019e
#define regMCathub_SYND2T0_BASE_IDX                                                                     0
#define regMCathub_CTL_MASKT0                                                                           0x01a0
#define regMCathub_CTL_MASKT0_BASE_IDX                                                                  0
#define regMCGathub_CTLT0                                                                               0x01a2
#define regMCGathub_CTLT0_BASE_IDX                                                                      0
#define regMCathub_PSPSTATT0                                                                            0x01a4
#define regMCathub_PSPSTATT0_BASE_IDX                                                                   0
#define regMCathub_LOG_MASKT0                                                                           0x01aa
#define regMCathub_LOG_MASKT0_BASE_IDX                                                                  0
#define regMCathub_FATAL_MASKT0                                                                         0x01ae
#define regMCathub_FATAL_MASKT0_BASE_IDX                                                                0
#define regMCathub_PSPADDRT0                                                                            0x01b0
#define regMCathub_PSPADDRT0_BASE_IDX                                                                   0
#define regMCathub_PSPMISC0T0                                                                           0x01b2
#define regMCathub_PSPMISC0T0_BASE_IDX                                                                  0
#define regMCathub_PSPSYNDT0                                                                            0x01b4
#define regMCathub_PSPSYNDT0_BASE_IDX                                                                   0
#define regMCathub_PSPSYND1T0                                                                           0x01ba
#define regMCathub_PSPSYND1T0_BASE_IDX                                                                  0
#define regMCathub_PSPSYND2T0                                                                           0x01bc
#define regMCathub_PSPSYND2T0_BASE_IDX                                                                  0
#define regMCathub_ERRINJECTT0                                                                          0x01be
#define regMCathub_ERRINJECTT0_BASE_IDX                                                                 0

#endif
