// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna3/sopp.h"
#include "rocjitsu/isa/arch/amdgpu/shared/execute_shared.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace rdna3 {

SNopSopp::SNopSopp(const MachineInst *inst)
    : Sopp("s_nop", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SNopSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SNopSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SSetkillSopp::SSetkillSopp(const MachineInst *inst)
    : Sopp("s_setkill", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SSetkillSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SSetkillSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SSethaltSopp::SSethaltSopp(const MachineInst *inst)
    : Sopp("s_sethalt", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SSethaltSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SSethaltSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SSleepSopp::SSleepSopp(const MachineInst *inst)
    : Sopp("s_sleep", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SSleepSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SSleepSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SSetInstPrefetchDistanceSopp::SSetInstPrefetchDistanceSopp(const MachineInst *inst)
    : Sopp("s_set_inst_prefetch_distance", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSetInstPrefetchDistanceSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SSetInstPrefetchDistanceSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SClauseSopp::SClauseSopp(const MachineInst *inst)
    : Sopp("s_clause", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SClauseSopp>()),
      simm16(16, OperandType::OPR_CLAUSE, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SClauseSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SDelayAluSopp::SDelayAluSopp(const MachineInst *inst)
    : Sopp("s_delay_alu", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SDelayAluSopp>()),
      simm16(16, OperandType::OPR_DELAY, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SDelayAluSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SWaitcntDepctrSopp::SWaitcntDepctrSopp(const MachineInst *inst)
    : Sopp("s_waitcnt_depctr", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitcntDepctrSopp>()),
      simm16(16, OperandType::OPR_WAITCNT_DEPCTR,
             reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SWaitcntDepctrSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SWaitcntSopp::SWaitcntSopp(const MachineInst *inst)
    : Sopp("s_waitcnt", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SWaitcntSopp>()),
      simm16(16, OperandType::OPR_WAITCNT, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SWaitcntSopp::execute_impl(amdgpu::Wavefront &wf) {
  uint16_t imm = static_cast<uint16_t>(simm16.encoding_value_);
  uint8_t exp = imm & 0x7;
  uint8_t lgkm = (imm >> 4) & 0x3F;
  uint8_t vm = (imm >> 10) & 0x3F;
  wf.set_wait_target(vm, lgkm, exp);
}

SWaitIdleSopp::SWaitIdleSopp(const MachineInst *inst)
    : Sopp("s_wait_idle", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitIdleSopp>()) {
  num_src_ = 0;
  num_dst_ = 0;
}

void SWaitIdleSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SWaitEventSopp::SWaitEventSopp(const MachineInst *inst)
    : Sopp("s_wait_event", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SWaitEventSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SWaitEventSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

STrapSopp::STrapSopp(const MachineInst *inst)
    : Sopp("s_trap", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<STrapSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void STrapSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SRoundModeSopp::SRoundModeSopp(const MachineInst *inst)
    : Sopp("s_round_mode", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SRoundModeSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SRoundModeSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SDenormModeSopp::SDenormModeSopp(const MachineInst *inst)
    : Sopp("s_denorm_mode", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SDenormModeSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SDenormModeSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SCodeEndSopp::SCodeEndSopp(const MachineInst *inst)
    : Sopp("s_code_end", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SCodeEndSopp>()) {
  num_src_ = 0;
  num_dst_ = 0;
}

void SCodeEndSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SBranchSopp::SBranchSopp(const MachineInst *inst)
    : Sopp("s_branch", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBranchSopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SBranchSopp::execute_impl(amdgpu::Wavefront &wf) {
  int16_t offset = static_cast<int16_t>(simm16.encoding_value_);
  wf.pc = wf.pc + 4 + static_cast<int64_t>(offset) * 4 - size_;
}

SCbranchScc0Sopp::SCbranchScc0Sopp(const MachineInst *inst)
    : Sopp("s_cbranch_scc0", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchScc0Sopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SCbranchScc0Sopp::execute_impl(amdgpu::Wavefront &wf) {
  if (!wf.read_scc()) {
    int16_t offset = static_cast<int16_t>(simm16.encoding_value_);
    wf.pc = wf.pc + 4 + static_cast<int64_t>(offset) * 4 - size_;
  }
}

SCbranchScc1Sopp::SCbranchScc1Sopp(const MachineInst *inst)
    : Sopp("s_cbranch_scc1", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchScc1Sopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SCbranchScc1Sopp::execute_impl(amdgpu::Wavefront &wf) {
  if (wf.read_scc()) {
    int16_t offset = static_cast<int16_t>(simm16.encoding_value_);
    wf.pc = wf.pc + 4 + static_cast<int64_t>(offset) * 4 - size_;
  }
}

SCbranchVcczSopp::SCbranchVcczSopp(const MachineInst *inst)
    : Sopp("s_cbranch_vccz", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchVcczSopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SCbranchVcczSopp::execute_impl(amdgpu::Wavefront &wf) {
  if (wf.vcc() == 0) {
    int16_t offset = static_cast<int16_t>(simm16.encoding_value_);
    wf.pc = wf.pc + 4 + static_cast<int64_t>(offset) * 4 - size_;
  }
}

SCbranchVccnzSopp::SCbranchVccnzSopp(const MachineInst *inst)
    : Sopp("s_cbranch_vccnz", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchVccnzSopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SCbranchVccnzSopp::execute_impl(amdgpu::Wavefront &wf) {
  if (wf.vcc() != 0) {
    int16_t offset = static_cast<int16_t>(simm16.encoding_value_);
    wf.pc = wf.pc + 4 + static_cast<int64_t>(offset) * 4 - size_;
  }
}

SCbranchExeczSopp::SCbranchExeczSopp(const MachineInst *inst)
    : Sopp("s_cbranch_execz", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchExeczSopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SCbranchExeczSopp::execute_impl(amdgpu::Wavefront &wf) {
  if (wf.exec() == 0) {
    int16_t offset = static_cast<int16_t>(simm16.encoding_value_);
    wf.pc = wf.pc + 4 + static_cast<int64_t>(offset) * 4 - size_;
  }
}

SCbranchExecnzSopp::SCbranchExecnzSopp(const MachineInst *inst)
    : Sopp("s_cbranch_execnz", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchExecnzSopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SCbranchExecnzSopp::execute_impl(amdgpu::Wavefront &wf) {
  if (wf.exec() != 0) {
    int16_t offset = static_cast<int16_t>(simm16.encoding_value_);
    wf.pc = wf.pc + 4 + static_cast<int64_t>(offset) * 4 - size_;
  }
}

SCbranchCdbgsysSopp::SCbranchCdbgsysSopp(const MachineInst *inst)
    : Sopp("s_cbranch_cdbgsys", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchCdbgsysSopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SCbranchCdbgsysSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SCbranchCdbguserSopp::SCbranchCdbguserSopp(const MachineInst *inst)
    : Sopp("s_cbranch_cdbguser", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchCdbguserSopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SCbranchCdbguserSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SCbranchCdbgsysOrUserSopp::SCbranchCdbgsysOrUserSopp(const MachineInst *inst)
    : Sopp("s_cbranch_cdbgsys_or_user", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchCdbgsysOrUserSopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SCbranchCdbgsysOrUserSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SCbranchCdbgsysAndUserSopp::SCbranchCdbgsysAndUserSopp(const MachineInst *inst)
    : Sopp("s_cbranch_cdbgsys_and_user", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCbranchCdbgsysAndUserSopp>()),
      simm16(16, OperandType::OPR_LABEL, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SCbranchCdbgsysAndUserSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SEndpgmSopp::SEndpgmSopp(const MachineInst *inst)
    : Sopp("s_endpgm", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SEndpgmSopp>()) {
  num_src_ = 0;
  num_dst_ = 0;
}

void SEndpgmSopp::execute_impl(amdgpu::Wavefront &wf) { wf.end(); }

SEndpgmSavedSopp::SEndpgmSavedSopp(const MachineInst *inst)
    : Sopp("s_endpgm_saved", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SEndpgmSavedSopp>()) {
  num_src_ = 0;
  num_dst_ = 0;
}

void SEndpgmSavedSopp::execute_impl(amdgpu::Wavefront &wf) { wf.end(); }

SEndpgmOrderedPsDoneSopp::SEndpgmOrderedPsDoneSopp(const MachineInst *inst)
    : Sopp("s_endpgm_ordered_ps_done", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SEndpgmOrderedPsDoneSopp>()) {
  num_src_ = 0;
  num_dst_ = 0;
}

void SEndpgmOrderedPsDoneSopp::execute_impl(amdgpu::Wavefront &wf) { wf.end(); }

SWakeupSopp::SWakeupSopp(const MachineInst *inst)
    : Sopp("s_wakeup", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SWakeupSopp>()) {
  num_src_ = 0;
  num_dst_ = 0;
}

void SWakeupSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SSetprioSopp::SSetprioSopp(const MachineInst *inst)
    : Sopp("s_setprio", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SSetprioSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SSetprioSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SSendmsgSopp::SSendmsgSopp(const MachineInst *inst)
    : Sopp("s_sendmsg", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SSendmsgSopp>()),
      simm16(16, OperandType::OPR_SENDMSG, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SSendmsgSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SSendmsghaltSopp::SSendmsghaltSopp(const MachineInst *inst)
    : Sopp("s_sendmsghalt", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SSendmsghaltSopp>()),
      simm16(16, OperandType::OPR_SENDMSG, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SSendmsghaltSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SIncperflevelSopp::SIncperflevelSopp(const MachineInst *inst)
    : Sopp("s_incperflevel", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SIncperflevelSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SIncperflevelSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SDecperflevelSopp::SDecperflevelSopp(const MachineInst *inst)
    : Sopp("s_decperflevel", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SDecperflevelSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void SDecperflevelSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

STtracedataSopp::STtracedataSopp(const MachineInst *inst)
    : Sopp("s_ttracedata", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<STtracedataSopp>()) {
  num_src_ = 0;
  num_dst_ = 0;
}

void STtracedataSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

STtracedataImmSopp::STtracedataImmSopp(const MachineInst *inst)
    : Sopp("s_ttracedata_imm", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<STtracedataImmSopp>()),
      simm16(16, OperandType::OPR_SIMM16, reinterpret_cast<const OpEncoding *>(inst)->simm16) {
  src_operands_[0] = &simm16;
  num_src_ = 1;
  num_dst_ = 0;
}

void STtracedataImmSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SIcacheInvSopp::SIcacheInvSopp(const MachineInst *inst)
    : Sopp("s_icache_inv", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SIcacheInvSopp>()) {
  num_src_ = 0;
  num_dst_ = 0;
}

void SIcacheInvSopp::execute_impl(amdgpu::Wavefront &wf) { (void)wf; }

SBarrierSopp::SBarrierSopp(const MachineInst *inst)
    : Sopp("s_barrier", reinterpret_cast<const OpEncoding *>(inst), make_exec_fn<SBarrierSopp>()) {
  num_src_ = 0;
  num_dst_ = 0;
}

void SBarrierSopp::execute_impl(amdgpu::Wavefront &wf) {
  amdgpu::execute_s_barrier_sopp(*this, wf);
}

} // namespace rdna3
} // namespace rocjitsu
