/*
************************************************************************************************************************
*
*  Copyright (C) 2025 Advanced Micro Devices, Inc.  All rights reserved.
*
***********************************************************************************************************************/

/**
************************************************************************************************************************
* @file  gfx13AT_LITE3MetaSwizzlePattern.h
* @brief meta swizzle pattern for gfx13.
************************************************************************************************************************
*/

#ifndef __GFX13_AT_LITE3_META_SWIZZLE_PATTERN_H__
#define __GFX13_AT_LITE3_META_SWIZZLE_PATTERN_H__

#include "addrinterface.h"

namespace rocr {
namespace Addr
{
namespace V3
{

	static constexpr ADDR3_EQUATION GFX13_SW_AT_LITE3_64KB_2D_Z = 
	{
		{
			{ 0, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  0
			{ 0, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  1
			{ 0, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  2
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  3 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  3
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  3 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  4
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  5 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  5
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  6 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  6
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  7 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  7
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  7 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  8
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  4 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  9
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  4 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit 10
			{ 2, { { ADDR3_EQ_OPERATOR::_XOR , ADDR3_EQ_CHANNEL::_X,  5 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  5 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit 11
			{ 4, { { ADDR3_EQ_OPERATOR::_AND , ADDR3_EQ_CHANNEL::_X,  5 }, { ADDR3_EQ_OPERATOR::_XOR , ADDR3_EQ_CHANNEL::_Y,  5 }, { ADDR3_EQ_OPERATOR::_XOR , ADDR3_EQ_CHANNEL::_X,  6 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  6 },   } }, // bit 12
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  8 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit 13
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  8 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit 14
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  9 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit 15
		},
		16, 3,
	};

	static constexpr ADDR3_EQUATION GFX13_SW_AT_LITE3_256KB_2D_Z = 
	{
		{
			{ 0, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  0
			{ 0, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  1
			{ 0, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  2
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  3 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  3
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  3 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  4
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  5 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  5
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  6 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  6
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  7 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  7
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  7 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  8
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  4 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit  9
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  4 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit 10
			{ 2, { { ADDR3_EQ_OPERATOR::_XOR , ADDR3_EQ_CHANNEL::_X,  5 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  5 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit 11
			{ 4, { { ADDR3_EQ_OPERATOR::_AND , ADDR3_EQ_CHANNEL::_X,  5 }, { ADDR3_EQ_OPERATOR::_XOR , ADDR3_EQ_CHANNEL::_Y,  5 }, { ADDR3_EQ_OPERATOR::_XOR , ADDR3_EQ_CHANNEL::_X,  6 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  6 },   } }, // bit 12
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  8 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit 13
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_Y,  8 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit 14
			{ 1, { { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  9 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 }, { ADDR3_EQ_OPERATOR::_NONE, ADDR3_EQ_CHANNEL::_X,  0 },   } }, // bit 15
		},
		16, 3,
	};


// Level 2
	static const ADDR3_EQUATION* GFX13_SW_AT_LITE3_256KB_SW[] = 
	{
		nullptr,
		&GFX13_SW_AT_LITE3_256KB_2D_Z,
		nullptr
	};
	static const ADDR3_EQUATION* GFX13_SW_AT_LITE3_64KB_SW[] = 
	{
		nullptr,
		&GFX13_SW_AT_LITE3_64KB_2D_Z,
		nullptr
	};

// Level 1
	static const ADDR3_EQUATION** GFX13_SW_AT_LITE3[] = 
	{
		nullptr,
		nullptr,
		GFX13_SW_AT_LITE3_64KB_SW,
		GFX13_SW_AT_LITE3_256KB_SW
	};

} // V3
} // Addr
} // rocr
#endif
