// Copyright (c) 2025-2026 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
// AUTO-GENERATED by the amdisa codegen pipeline. DO NOT EDIT.
// See lib/python/amdisa/README.md for regeneration instructions.

#include "rocjitsu/isa/arch/amdgpu/rdna1/sopc.h"
#include "rocjitsu/vm/amdgpu/wavefront.h"
#include "util/data_types.h"
#include "util/except.h"
#include <algorithm>
#include <bit>
#include <cmath>
#include <limits>

namespace rocjitsu {
namespace rdna1 {

SCmpEqI32Sopc::SCmpEqI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpEqI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpEqI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  int32_t s0 = static_cast<int32_t>(ssrc0.read_scalar(wf));
  int32_t s1 = static_cast<int32_t>(ssrc1.read_scalar(wf));
  wf.write_scc(s0 == s1);
}

SCmpLgI32Sopc::SCmpLgI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLgI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpLgI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  int32_t s0 = static_cast<int32_t>(ssrc0.read_scalar(wf));
  int32_t s1 = static_cast<int32_t>(ssrc1.read_scalar(wf));
  wf.write_scc(s0 != s1);
}

SCmpGtI32Sopc::SCmpGtI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_gt_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGtI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpGtI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  int32_t s0 = static_cast<int32_t>(ssrc0.read_scalar(wf));
  int32_t s1 = static_cast<int32_t>(ssrc1.read_scalar(wf));
  wf.write_scc(s0 > s1);
}

SCmpGeI32Sopc::SCmpGeI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ge_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGeI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpGeI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  int32_t s0 = static_cast<int32_t>(ssrc0.read_scalar(wf));
  int32_t s1 = static_cast<int32_t>(ssrc1.read_scalar(wf));
  wf.write_scc(s0 >= s1);
}

SCmpLtI32Sopc::SCmpLtI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lt_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLtI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpLtI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  int32_t s0 = static_cast<int32_t>(ssrc0.read_scalar(wf));
  int32_t s1 = static_cast<int32_t>(ssrc1.read_scalar(wf));
  wf.write_scc(s0 < s1);
}

SCmpLeI32Sopc::SCmpLeI32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_le_i32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLeI32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpLeI32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  int32_t s0 = static_cast<int32_t>(ssrc0.read_scalar(wf));
  int32_t s1 = static_cast<int32_t>(ssrc1.read_scalar(wf));
  wf.write_scc(s0 <= s1);
}

SCmpEqU32Sopc::SCmpEqU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpEqU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpEqU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint32_t s0 = ssrc0.read_scalar(wf);
  uint32_t s1 = ssrc1.read_scalar(wf);
  wf.write_scc(s0 == s1);
}

SCmpLgU32Sopc::SCmpLgU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLgU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpLgU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint32_t s0 = ssrc0.read_scalar(wf);
  uint32_t s1 = ssrc1.read_scalar(wf);
  wf.write_scc(s0 != s1);
}

SCmpGtU32Sopc::SCmpGtU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_gt_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGtU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpGtU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint32_t s0 = ssrc0.read_scalar(wf);
  uint32_t s1 = ssrc1.read_scalar(wf);
  wf.write_scc(s0 > s1);
}

SCmpGeU32Sopc::SCmpGeU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_ge_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpGeU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpGeU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint32_t s0 = ssrc0.read_scalar(wf);
  uint32_t s1 = ssrc1.read_scalar(wf);
  wf.write_scc(s0 >= s1);
}

SCmpLtU32Sopc::SCmpLtU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lt_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLtU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpLtU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint32_t s0 = ssrc0.read_scalar(wf);
  uint32_t s1 = ssrc1.read_scalar(wf);
  wf.write_scc(s0 < s1);
}

SCmpLeU32Sopc::SCmpLeU32Sopc(const MachineInst *inst)
    : Sopc("s_cmp_le_u32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLeU32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpLeU32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint32_t s0 = ssrc0.read_scalar(wf);
  uint32_t s1 = ssrc1.read_scalar(wf);
  wf.write_scc(s0 <= s1);
}

SBitcmp0B32Sopc::SBitcmp0B32Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp0_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitcmp0B32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SBitcmp0B32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t bit = ssrc1.read_scalar(wf) & 31u;
  wf.write_scc(!(val & (1ULL << bit)));
}

SBitcmp1B32Sopc::SBitcmp1B32Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp1_b32", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitcmp1B32Sopc>()),
      ssrc0(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SBitcmp1B32Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint32_t val = ssrc0.read_scalar(wf);
  uint32_t bit = ssrc1.read_scalar(wf) & 31u;
  wf.write_scc((val & (1ULL << bit)) != 0);
}

SBitcmp0B64Sopc::SBitcmp0B64Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp0_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitcmp0B64Sopc>()),
      ssrc0(64, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SBitcmp0B64Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t val = ssrc0.read_scalar64(wf);
  uint32_t bit = ssrc1.read_scalar(wf) & 63u;
  wf.write_scc(!(val & (1ULL << bit)));
}

SBitcmp1B64Sopc::SBitcmp1B64Sopc(const MachineInst *inst)
    : Sopc("s_bitcmp1_b64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SBitcmp1B64Sopc>()),
      ssrc0(64, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(32, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        32, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SBitcmp1B64Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t val = ssrc0.read_scalar64(wf);
  uint32_t bit = ssrc1.read_scalar(wf) & 63u;
  wf.write_scc((val & (1ULL << bit)) != 0);
}

SCmpEqU64Sopc::SCmpEqU64Sopc(const MachineInst *inst)
    : Sopc("s_cmp_eq_u64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpEqU64Sopc>()),
      ssrc0(64, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpEqU64Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t s0 = ssrc0.read_scalar64(wf);
  uint64_t s1 = ssrc1.read_scalar64(wf);
  wf.write_scc(s0 == s1);
}

SCmpLgU64Sopc::SCmpLgU64Sopc(const MachineInst *inst)
    : Sopc("s_cmp_lg_u64", reinterpret_cast<const OpEncoding *>(inst),
           make_exec_fn<SCmpLgU64Sopc>()),
      ssrc0(64, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc0),
      ssrc1(64, OperandType::OPR_SSRC_NOLDS, reinterpret_cast<const OpEncoding *>(inst)->ssrc1) {
  src_operands_[0] = &ssrc0;
  src_operands_[1] = &ssrc1;
  num_src_ = 2;
  num_dst_ = 0;
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc0 == 255)
    ssrc0 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
  if (reinterpret_cast<const OpEncoding *>(inst)->ssrc1 == 255)
    ssrc1 = Operand(
        64, OperandType::OPR_SIMM32,
        static_cast<int>(reinterpret_cast<const SopcInstLiteralMachineInst *>(inst)->simm32));
}

void SCmpLgU64Sopc::execute_impl(amdgpu::Wavefront &wf) {
  uint64_t s0 = ssrc0.read_scalar64(wf);
  uint64_t s1 = ssrc1.read_scalar64(wf);
  wf.write_scc(s0 != s1);
}

} // namespace rdna1
} // namespace rocjitsu
